### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by PAk-CatchFire** [cpuimage/BluesteinCrz#1]

**Comment by PAk-CatchFire** [comment]
Hello.

I wonder if you have an example for this library. I am working on my embedded sw thesis, and I really like your code, to keep it as simple as possible.
Regards

**Comment by cpuimage** [comment]
sorry, no more example here, you can read the code to understand the usage.

**Comment by PAk-CatchFire** [comment]
Than you @cpuimage 
I want to use it like this example, for zooming in a specific range of the FFT. Do you  think it is possible?

http://ltfat.github.io/doc/fourier/chirpzt.html


Instead, you are using this code:
```
for (size_t i = 1; i < n; i = 2 * i) {

        const float delta = PI / i;

        for (int j = 0; j < i; j++) {
```

What is the purpose of your code?

Regards

**Comment by cpuimage** [comment]
I don't quite understand the principle of zoom fft algorithm, maybe you can refer to the link [ZoomFFT](https://www.arc.id.au/ZoomFFT.html)

**Comment by PAk-CatchFire** [comment]
Thank you @cpuimage 

Why are you using Bluestein CZT transform? Are you using it  as a regular FFT then?

**Comment by cpuimage** [comment]
@PAk-CatchFire In general, I use [stb_fft](https://github.com/cpuimage/stb_fft)
